### ISSUE TITLE
[게시판] 게시판에 추가가 안되는 현상

### ISSUE THREAD

**Issue by sw2park** [sw2park/LastReviewFinder#46]
**이슈 현상**

---
**이슈 재현 절차**
1.
2

![image](https://github.com/user-attachments/assets/1cb5e29c-f847-4e81-8957-89e4366f6229)

---
**실제 결과(이슈 동작)**
- 

---
**기대 결과**
 - 게시판에 추가가 되야합니다 

밥|치킨
-|-
맛있다|맛없다

---
**참고 사항**
- 재현 빈도
- 30% 

- 기타

---
**테스트 환경**
> chrome 버전
- Chrome이 최신 버전임
버전 129.0.6668.90(공식 빌드) (64비트)

**Comment by sw2park** [comment]
~언제 했는데 이슈 재현이 안된다.

**Comment by sw2park** [comment]
[여기 참고](https://github.com/sw2park/LastReviewFinder/issues/46)

**Comment by sw2park** [comment]
~일자 다시 확인했을때 재현되어 리오픈함

**Comment by Jisoo-im** [comment]
241008 16:45 다시수정했어요
