### ISSUE TITLE
[헤더-영화 추천 페이지 안에서] 영화 추천 페이지 안에 헤더에서 아이디 비밀번호가 다르다는 alert 창이 선택마다 뜸

### ISSUE THREAD

**Issue by kybxdc** [sw2park/LastReviewFinder#49]
**이슈 현상**
영화 추천 페이지 안에 헤더에서 "아이디, 비밀번호가 맞지 않습니다." alert 창이 선택마다 발생 함
---
**이슈 재현 절차**
1. 영화 추천 클릭
2. 라운드 선택
3. 시작하기 클릭
4. 영화 선택 시작 시 alert 창 발생
5. 이후 영화 선택 시 마다 계속해서 alert 창 이슈 발생

---
**실제 결과(이슈 동작)**
- 영화 선택 마다 "아이디, 비밀번호가 맞지 않습니다." alert 창 발생

---
**기대 결과**
 - 추천 페이지에서 영화 선택 시 로그인 문제가 발생하지 않아야 함

---
**참고 사항**
- 재현 빈도: 영화 선택 마다 이슈 발생

- 기타

---
**테스트 환경**
> chrome 버전
-버전 129.0.6668.90(공식 빌드) (64비트)

**Comment by kybxdc** [comment]
develop에 올라가 있는 건 rec_pick.jsp의 header 부분이 버그로 인해 임시로 주석 처리 되어있으니 확인 바랍니다.

**Comment by sw2park** [comment]
버그 재현 확인하여 수정하고 있습니다.
수정 후 코멘트 추가하겠습니다.

**Comment by Jisoo-im** [comment]
이거 로그인할때 세션에서 패스워드 값 지우도록 되어있는데 혹시 그거때문아닐까요? 로그인페이지랑 연관있는거같아서 남깁니당....

**Comment by sw2park** [comment]
수정 완료되어 확인 부탁드립니다.
[링크](https://github.com/sw2park/LastReviewFinder/commit/cdf81e2be155d6bbb9b93792578d343378d9b672)

**Comment by kybxdc** [comment]
> 수정 완료되어 확인 부탁드립니다. [링크](https://github.com/sw2park/LastReviewFinder/commit/cdf81e2be155d6bbb9b93792578d343378d9b672)

정상 작동 확인 했습니다.
